import PropertyManagerSignInComponent from "@/components/PANEL/auth/property-manager-auth/propertyManagerSignin/propertyManagerSignin";
export const metadata = {
  title: "BizHome Solutions | Property Manager Sign In",
  description: "Generated by create next app",
};
export default function PropertyManagerSignin() {
  return <PropertyManagerSignInComponent />;
}
