import TechnicianSignIn from "@/components/PANEL/auth/technician-auth/technicianSignIn/technicianSignIn";
export const metadata = {
  title: "BizHome Solutions | Technician Sign In",
  description: "Generated by create next app",
};
export default function TechnicianSignInPage() {
  return <TechnicianSignIn />;
}
