import TechnicianForgotPasswordForm from "@/components/PANEL/auth/technician-auth/technicianForgotPassword/technicianForgotPassword";

export const metadata = {
  title: "BizHome Solutions | Technician Forgot Password",
  description: "Generated by create next app",
};

export default function TechnicianForgotPasswordPage() {
  return <TechnicianForgotPasswordForm />;
}
