import TechnicianSignUp from "@/components/PANEL/auth/technician-auth/technicianSignUp/technicianSignUp";

export const metadata = {
  title: "BizHome Solutions | Technician Sign Up",
  description: "Generated by create next app",
};

export default function TechnicianSignUpPage() {
  return <TechnicianSignUp />;
}
