import PropertyManagerActivationComponent from "@/components/PANEL/auth/property-manager-auth/propertyManagerActivation/propertyManagerActivation";
export const metadata = {
  title: "BizHome Solutions | Property Manager Activation",
  description: "Generated by create next app",
};
export default function PropertyManagerActivation() {
  return <PropertyManagerActivationComponent />;
}
