import FormDemoComponent from "@/components/PANEL/auth/formDemo/formDemo";
export const metadata = {
  title: "BizHome Solutions | Request Demo ",
  description: "Generated by create next app",
};
export default function FormDemo() {
  return <FormDemoComponent />;
}
