import PropertyManagerForgotPasswordForm from "@/components/PANEL/auth/property-manager-auth/propertyManagerForgotPassword/propertyManagerForgotPassword";

export const metadata = {
  title: "BizHome Solutions | Property Manager Forgot Password",
  description: "Generated by create next app",
};

export default function PropertyManagerForgotPasswordPage() {
  return <PropertyManagerForgotPasswordForm />;
}
